# https://hugoloveit.com/zh-cn/theme-documentation-basics/
baseURL = 'https://googlc.github.io'
languageCode = 'en-us'
languageName = "English"
title = 'LAST'
theme = 'LoveIt'



hasCJKLanguage = true
# 默认每页列表显示的文章数目
paginate = 12
# 谷歌分析代号 [UA-XXXXXXXX-X]
googleAnalytics = ""
# 版权描述，仅仅用于 SEO
copyright = ""

# 是否使用 robots.txt
#enableRobotsTXT = true
# 忽略一些构建错误
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

[author]
name = " "
email = "lingong@mail.com"
link = ""

[params.page.share]
  enable = true
  Twitter = true
  Facebook = true
  Linkedin = true
  HackerNews = true
  Reddit = true
  Line = true
  Instapaper = false
  Pocket = false
  Weibo = true
  Blogger = true


# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false



[params.social]
  GitHub = "googlc"
  Zhihu = "shen-yi-sheng-28"
  RSS = true

[params.page.comment]
  # giscus comment 评论系统设置 (https://giscus.app/zh-CN)
  [params.page.comment.giscus]
  # 你可以参考官方文档来使用下列配置
  enable = false
  repo = ""
  repoId = ""
  category = "Announcements"
  categoryId = ""
  # 为空时自动适配当前主题 i18n 配置
  lang = ""
  mapping = "pathname"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  lazyLoading = false
  lightTheme = "light"
  darkTheme = "dark"
#[params.cdn]
#  # CDN 数据文件名称, 默认不启用
#  # ["jsdelivr.yml"]
#  data = ""

#[outputs]
#  home = ["HTML", "RSS", "JSON"]
#[params.search]
#  enable = true
#  # 搜索引擎的类型 ["lunr", "algolia"]
#  type = "lunr"
#  # 文章内容最长索引长度
#  contentLength = 4000
#  # 搜索框的占位提示语
#  placeholder = ""
#  # LoveIt 新增 | 0.2.1 最大结果数目
#  maxResultLength = 10
#  # LoveIt 新增 | 0.2.3 结果内容片段长度
#  snippetLength = 50
#  # LoveIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
#  highlightTag = "em"
#  # LoveIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
#  absoluteURL = false
#  [params.search.algolia]
#  index = ""
#  appID = ""
#  searchKey = ""